name: Build all packages for mipsel_24kc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set branch
      - name: Set branch
        run: |
          BRANCH="${GITHUB_BASE_REF:-master}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      # 3. Add helloworld feed
      - name: Add helloworld feed
        run: |
          sed -i "/helloworld/d" feeds.conf.default
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a -f

      # 4. Detect all packages
      - name: Detect packages
        run: |
          PACKAGES=$(find package/ feeds/ -maxdepth 2 -name Makefile | \
                     sed -e 's@\(.*\)/Makefile@\1@' | tr '\n' ' ')
          echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
          echo "Detected packages: $PACKAGES"

      # 5. Build all packages
      - name: Build packages
        uses: immortalwrt/gh-action-sdk@v5
        env:
          ARCH: mipsel_24kc
          FEEDNAME: packages_ci
          V: s

      # 6. Collect all built .ipk files
      - name: Collect packages
        run: cp bin/packages/mipsel_24kc/packages_ci/*.ipk . || true

      # 7. Generate PKG-INFO metadata
      - name: Generate PKG-INFO
        run: |
          MERGE_ID=$(git rev-parse --short HEAD)
          ARCHIVE_NAME=mipsel_24kc-$MERGE_ID
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

          # создаём PKG-INFO
          cat << _EOF_ > PKG-INFO
Metadata-Version: 2.1
Name: $ARCHIVE_NAME
Version: $BRANCH
Author: $GITHUB_ACTOR
Summary: All packages for mipsel_24kc
Platform: mipsel_24kc

Modified packages:
 _EOF_

          # добавляем все пакеты в PKG-INFO
          for p in $PACKAGES; do
            echo "  $p" >> PKG-INFO
          done

          echo >> PKG-INFO
          echo "Full file listing:" >> PKG-INFO
          ls -al *.ipk >> PKG-INFO || true
          cat PKG-INFO

      # 8. Upload all .ipk and PKG-INFO as artifacts
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}-packages
          path: |
            *.ipk
            PKG-INFO
